name: Application_CI_Workflow
run-name: conversion-app:${{ github.event.inputs.App_Version }}

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      App_Version:
        description: 'Input App Version to Tag and Release'
        required: true
        type: string
        default: "latest"

jobs:
  Build_And_Test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt' # 'adopt', 'openjdk', 'temurin'
          java-version: '21'

      - name: Setup Maven
        uses: s4u/maven-settings-action@v2
        with:
          maven-version: '3.9'

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn clean package

      - name: Test with Maven
        run: mvn test

      - name: Docker Build
      
        run: |
          docker build -t conversion-app:${{ github.event.inputs.App_Version }} -f ${{github.workspace}}/Dockerfile .
          

      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker Tag and Push
        run: |
          docker tag conversion-app:${{ github.event.inputs.App_Version }} ${{ secrets.DOCKER_USERNAME }}/conversion-app:${{ github.event.inputs.App_Version }}
          docker push ${{ secrets.DOCKER_USERNAME }}/conversion-app:${{ github.event.inputs.App_Version }}
