name : Conversion App Deployment
run-name: ${{ github.event.inputs.App_Env }}:Deploy-${{ github.event.inputs.App_Name }}:${{ github.event.inputs.App_Version }}

on:
  workflow_dispatch:
    inputs:
      App_Name:
        description: 'Input App Name be deployed'
        required: true
        type: string
        default: "conversion-app"
      App_Version:
        description: 'Input App Version to Tag and Release'
        required: true
        type: string
        default: "1.0.0"
      App_Env:
        description: 'Target App Environment to Deploy'
        required: true
        type: choice
        default: "dev"
        options:
          - dev
          - stg
          - prod
  push:
    branches:
      - main

jobs:
  App_Deploy:
    name: Create or Update Infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout App Repository
        uses: actions/checkout@v4

      - name: Checkout Infra Repository
        uses: actions/checkout@v4
        with:
          repository: 'hbekal005/conversion-app-infra'
          token: ${{ secrets.GIT_INFRA_REPO_TOKEN }}
          ref: 'main'
          path: 'conversion-app-infra'

      - name: Setup Terraform
        id: setup-terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.10'


      - name: Terraform Init for Backend Prerequisites
        if: success()
        id: terraform-backend-init
        run: |
            cd ${{ github.workspace }}/conversion-app-infra/backend-infra-prerequisites
            terraform init

      - name: Terraform Validate for Backend Prerequisites
        id: terraform-backend-validate
        if: success()
        run: |
            cd ${{ github.workspace }}/conversion-app-infra/backend-infra-prerequisites
            terraform validate

      - name: Terraform Plan for Backend Prerequisites
        id: terraform-backend-plan
        if: success()
        run: |
            cd ${{ github.workspace }}/conversion-app-infra/backend-infra-prerequisites
            terraform plan \
              -var 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}' \
              -var 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
              -out=backend-tfplan

      - name: Terraform Apply for Backend Prerequisites
        id: terraform-backend-apply
        if: success()
        run: | 
            cd ${{ github.workspace }}/conversion-app-infra/backend-infra-prerequisites
            terraform apply -auto-approve "backend-tfplan"
    